/**
 * Golden Dragon - Core Execution Service
 * Handles the handoff between Strategy Agents and the Execution/Risk Agent.
 */

// --- Interfaces & Types ---

/**
 * Represents the state and limits of the Risk/Execution Agent.
 */
export interface RiskLimits {
  /** Maximum single trade size in USD */
  maxOrderSizeUsd: number;
  /** Maximum allowable loss per day in USD */
  maxDailyLossUsd: number;
  /** Maximum total exposure across all open positions in USD */
  maxTotalExposureUsd: number;
  /** Maximum number of open positions allowed simultaneously */
  maxOpenPositions: number;
}

/**
 * Represents the current state of our risk tracking.
 */
export interface RiskState {
  currentDailyLossUsd: number;
  currentTotalExposureUsd: number;
  openPositionsCount: number;
}

/**
 * Payload generated by the Strategy Agent.
 */
export interface TradeSignal {
  /** Unique identifier for the signal */
  signalId: string;
  /** Asset symbol (e.g., 'BTC/USD', 'NVDA') */
  symbol: string;
  /** Side of the trade */
  side: 'buy' | 'sell' | 'long' | 'short';
  /** Requested order size in USD */
  sizeUsd: number;
  /** Expected price at time of signal generation */
  targetPrice: number;
  /** Timestamp when the signal was generated */
  timestamp: number;
  /** Strategy identifier */
  strategyId: string;
}

/**
 * Result of an execution attempt.
 */
export interface ExecutionResult {
  signalId: string;
  status: 'filled' | 'rejected' | 'failed';
  executedPrice?: number;
  executedSizeUsd?: number;
  reason?: string;
  timestamp: number;
}

// --- Mock Exchange Interface ---

/**
 * Mocking an external Exchange API for demonstration purposes.
 */
class MockExchangeApi {
  /**
   * Simulates submitting an order to an exchange.
   * Rejects pseudo-randomly to demonstrate exponential backoff.
   */
  async submitOrder(signal: TradeSignal): Promise<{ price: number; size: number }> {
    // Simulate network delay
    await new Promise(resolve => setTimeout(resolve, Math.random() * 200 + 50));
    
    // Simulate rate limit or random API failure (20% chance)
    if (Math.random() < 0.2) {
      const error = new Error('Rate limit exceeded');
      (error as any).status = 429;
      throw error;
    }

    // Return fake execution
    const slippage = 1 + (Math.random() * 0.002 - 0.001); // +/- 0.1% slippage
    return {
      price: signal.targetPrice * slippage,
      size: signal.sizeUsd
    };
  }
}

// --- Core Execution Service ---

export class TradingExecutor {
  private limits: RiskLimits;
  private state: RiskState;
  private exchangeApi: MockExchangeApi;

  // Active signal processing queue tracking
  private isProcessing: boolean = false;
  private signalQueue: TradeSignal[] = [];

  constructor(limits: RiskLimits, initialState?: RiskState) {
    this.limits = limits;
    this.state = initialState || {
      currentDailyLossUsd: 0,
      currentTotalExposureUsd: 0,
      openPositionsCount: 0
    };
    this.exchangeApi = new MockExchangeApi();
  }

  /**
   * Enqueues a signal from the Strategy Agent for asynchronous processing.
   * This decoupled ingestion ensures we do not block the strategy thread.
   */
  public enqueueSignal(signal: TradeSignal): void {
    this.signalQueue.push(signal);
    this.processQueue().catch(err => {
      console.error(`[TradingExecutor] Background processing error:`, err);
    });
  }

  /**
   * Continuously processes the queue. Strictly sequential per pair/overall 
   * to avoid race conditions on risk state updates.
   */
  private async processQueue(): Promise<void> {
    // Prevent concurrent queue processing loops
    if (this.isProcessing) return;
    this.isProcessing = true;

    try {
      while (this.signalQueue.length > 0) {
        // Dequeue the oldest signal safely
        const signal = this.signalQueue.shift();
        if (!signal) continue;

        await this.handleSignal(signal);
      }
    } finally {
      this.isProcessing = false;
    }
  }

  /**
   * Handles the complete lifecycle of a single trade signal.
   */
  private async handleSignal(signal: TradeSignal): Promise<ExecutionResult> {
    console.log(`[TradingExecutor] Evaluating signal ${signal.signalId} for ${signal.symbol}`);

    // 1. Strict pre-trade risk checks
    const riskCheckPassed = this.validateRisk(signal);
    if (!riskCheckPassed.valid) {
      console.warn(`[TradingExecutor] Signal ${signal.signalId} REJECTED by Risk Agent: ${riskCheckPassed.reason}`);
      return {
        signalId: signal.signalId,
        status: 'rejected',
        reason: riskCheckPassed.reason,
        timestamp: Date.now()
      };
    }

    // 2. Execution with Exponential Backoff
    try {
      const execData = await this.executeWithRetry(signal);
      
      // Update state upon successful fill
      // In a real system, side (buy vs sell) logic determines exposure mapping.
      // Here we assume a simple increment for demonstration of risk bounding.
      this.state.currentTotalExposureUsd += execData.size;
      this.state.openPositionsCount += 1;

      console.log(`[TradingExecutor] Signal ${signal.signalId} FILLED at $${execData.price.toFixed(2)}`);
      
      return {
        signalId: signal.signalId,
        status: 'filled',
        executedPrice: execData.price,
        executedSizeUsd: execData.size,
        timestamp: Date.now()
      };
    } catch (error: any) {
      console.error(`[TradingExecutor] Signal ${signal.signalId} FAILED completely after retries: ${error.message}`);
      return {
        signalId: signal.signalId,
        status: 'failed',
        reason: error.message,
        timestamp: Date.now()
      };
    }
  }

  /**
   * Risk Agent Logic: Validates if the trade adheres to all constraints.
   */
  private validateRisk(signal: TradeSignal): { valid: boolean; reason?: string } {
    // Check 1: Max Order Size
    if (signal.sizeUsd > this.limits.maxOrderSizeUsd) {
      return { valid: false, reason: `Requested size (${signal.sizeUsd} USD) exceeds max limit (${this.limits.maxOrderSizeUsd} USD) `};
    }

    // Check 2: Daily Loss Cap (hard stop limit)
    if (this.state.currentDailyLossUsd >= this.limits.maxDailyLossUsd) {
      return { valid: false, reason: `Daily limit reached. Loss (${this.state.currentDailyLossUsd}) >= Max (${this.limits.maxDailyLossUsd})` };
    }

    // Check 3: Total Exposure Limit
    const newExposure = this.state.currentTotalExposureUsd + signal.sizeUsd;
    if (newExposure > this.limits.maxTotalExposureUsd) {
      return { valid: false, reason: `Total exposure cap exceeded. Projected: ${newExposure}, Max: ${this.limits.maxTotalExposureUsd}` };
    }

    // Check 4: Open Positions Cap
    if (this.state.openPositionsCount >= this.limits.maxOpenPositions) {
      return { valid: false, reason: `Max open positions reached (${this.limits.maxOpenPositions})` };
    }

    return { valid: true };
  }

  /**
   * Executes the trade payload securely against the exchange with jittered exponential backoff.
   */
  private async executeWithRetry(
    signal: TradeSignal,
    maxRetries: number = 3,
    baseDelayMs: number = 500
  ): Promise<{ price: number; size: number }> {
    let attempt = 0;

    while (attempt <= maxRetries) {
      try {
        // Attempt external network call
        const res = await this.exchangeApi.submitOrder(signal);
        return res;
      } catch (error: any) {
        attempt++;

        // Only retry on rate limits or 5xx server errors, not on semantic bad requsts (e.g. 400 Insufficient Funds)
        const isRetryable = error.status === 429 || error.status >= 500;
        
        if (!isRetryable || attempt > maxRetries) {
          throw new Error(`Execution failed: ${error.message}. Attempt ${attempt}/${maxRetries}`);
        }

        // Exponential backoff with jitter to strictly avoid 'thundering herd' spikes
        const backoffMs = baseDelayMs * Math.pow(2, attempt - 1);
        const jitter = Math.random() * 200; // 0-200ms randomness
        const delay = backoffMs + jitter;

        console.warn(`[TradingExecutor] Execution rate-limited/failed. Retrying ${attempt}/${maxRetries} in ${delay.toFixed(0)}ms...`);
        await new Promise(resolve => setTimeout(resolve, delay));
      }
    }
    
    throw new Error('Unreachable exception fallback');
  }

  // --- Utility Getters ---
  
  public getRiskState(): RiskState {
    return { ...this.state };
  }
}
